packages:
  - "packages/*"
  - "apps/*"
catalogs:
  hoisted:
    "@itwin/appui-abstract": "4.10.2"
    "@itwin/appui-react": "4.17.4"
    "@itwin/components-react": "4.17.0"
    "@itwin/core-backend": "4.10.0-dev.20"
    "@itwin/core-bentley": "4.10.0-dev.20"
    "@itwin/core-common": "4.10.0-dev.20"
    "@itwin/core-frontend": "4.10.0-dev.20"
    "@itwin/core-geometry": "4.10.0-dev.20"
    "@itwin/core-markup": "4.10.0-dev.20"
    "@itwin/core-orbitgt": "4.10.0-dev.20"
    "@itwin/core-quantity": "4.10.0-dev.20"
    "@itwin/core-react": "4.17.0"
    "@itwin/core-telemetry": "4.10.0-dev.20"
    "@itwin/ecschema-editing": "4.10.0-dev.20"
    "@itwin/ecschema-locaters": "4.10.0-dev.20"
    "@itwin/ecschema-metadata": "4.10.0-dev.20"
    "@itwin/ecschema-rpcinterface-common": "4.10.0-dev.20"
    "@itwin/ecschema-rpcinterface-impl": "4.10.0-dev.20"
    "@itwin/editor-backend": "4.10.0-dev.20"
    "@itwin/editor-common": "4.10.0-dev.20"
    "@itwin/editor-frontend": "4.10.0-dev.20"
    "@itwin/frontend-devtools": "4.10.0-dev.20"
    "@itwin/imodel-components-react": "4.17.0"
    "@itwin/itwinui-react": "3.15.4"
    "@itwin/map-layers-auth": "4.10.0-dev.20"
    "@itwin/map-layers-formats": "4.10.0-dev.20"
    "@itwin/presentation-backend": "4.10.0-dev.20"
    "@itwin/presentation-common": "4.10.0-dev.20"
    "@itwin/presentation-components": "5.4.1"
    "@itwin/presentation-frontend": "4.10.0-dev.20"
    "react": "17.0.2"
    "react-dom": "17.0.2"
    "react-redux": "7.2.9"
  editing:
    "@bentley/editing-backend": "0.1.0-dev.13"
    "@bentley/editing-common": "0.1.0-dev.13"
    "@bentley/editing-frontend": "0.1.0-dev.13"
  imodels:
    "@itwin/imodels-access-backend": "^5.2.0"
    "@itwin/imodels-client-authoring": "^5.6.0"
  ui:
    "@itwin/itwinui-icons-react": "^2.8.0"
    "@itwin/measure-tools-react": "^0.17.0"
    "@itwin/property-grid-react": "^1.8.0"
    "@itwin/tree-widget-react": "^2.3.1"
  babel:
    "@babel/plugin-transform-modules-commonjs": "^7.24.1"
    "@babel/preset-env": "^7.24.5"
    "@babel/preset-typescript": "^7.24.1"
  testing:
    "@bentley/studio-apps-testing": "^0.1.35"
    "@jest/globals": "^29.2.0"
    "@types/jest": "^29.5.13"
    "@types/node": "^18.19.42"
    "@types/react": "^17.0.80"
    "babel-jest": "^29.7.0"
    "jest": "^29.7.0"
    "ts-jest": "^29.2.3"
    "unique-names-generator": "^4.7.1"
  dev:
    "@itwin/build-tools": "4.10.0-dev.20"
    "typescript": "~5.0.4"
    "dotenv": "^16.4.5"
    "redux": "^4.2.1"
st": "^29.7.0"
    "jest": "^29.7.0"
    "ts-jest": "^29.2.3"
    "unique-names-generator": "^4.7.1"
  dev:
    "@itwin/build-tools": "4.10.0-dev.20"
    "typescript": "~5.0.4"
    "dotenv": "^16.4.5"
    "redux": "^4.2.1"
