name: Check package.json

on: 
<<<<<<< HEAD
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
=======
  workflow_dispatch:

>>>>>>> fa3e1cf457e2b58c78f0e16d3733286645070a71

jobs:
  check-package-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: actionstestorg/test2
<<<<<<< HEAD
        token: ${{ secrets.TOEKN_3 }}

    - name: Check for package.json
      run: |
        if [ -f package.json ]; then
          echo "package.json exists."
        else
          echo "package.json does not exist."
          exit 1
        fi
=======
        token: ${{ secrets.TOKEN_3 }}


    - name: Check for package.json and get version
      run: |
          if [ -f package.json ]; then
            echo "package.json exists."
            package_version=$(jq -r '.version' package.json)
            echo "Package version: $package_version"
          else
            echo "package.json does not exist."
            exit 1
          fi

    - name: Print package.json
      run: cat package.json
>>>>>>> fa3e1cf457e2b58c78f0e16d3733286645070a71
