name: Run on PR labeled with release

on:
  pull_request_target:
    types: [labeled]

jobs:
  run-on-release-label:
    if: contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a script
        run: echo "This PR is labeled with 'release'. Running the workflow..."
