name: Check Change Files

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main,test]

jobs:
  check-change-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check for change files
      run: |
        if ! git diff --name-only origin/main | grep -q '^change/'; then
          echo "No change file found in the 'change' folder."
          exit 1
        fi
