name: Get Commit History

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  get-commit-history:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get commit history
      run: |
        git fetch --unshallow
        git log
        git log --pretty=format:"%h %s" > commit_history.txt
        cat commit_history.txt

    - name: Find commit with 'release'
      run: |
        git log --pretty=format:"%h - %an, %ar : %s" | grep -i 'release' > Release_Commits.txt
        git add Release_Commits.txt 
        git commit -m "updated Release Commits file"
        git push -u origin test
