name: Get Commit History

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  get-commit-history:
    
    runs-on: ubuntu-latest
    permissions:
      workflows: write
      contents: write
      actions: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get commit history
      run: |
        git fetch --unshallow
        git log
        git log --pretty=format:"%h %s" > commit_history.txt
        cat commit_history.txt

    - name: Find commit with 'release'
      run: |
        git config user.name "Saurabh Talele"
        git config user.email  "Saurabh.Talele@bentley.com"
        git log --pretty=format:"%h %s" | grep -i 'release' > Release_Commits.txt  

    - name: Tag commits with 'release'
      run: |
          while IFS= read -r line; do
          commit_id=$(echo $line | awk '{print $1}')
          tag_name=$(echo $line | awk '{print $NF}')
          git tag -a "$tag_name" -m "Tagging release commit" "$commit_id"
          git push origin "$tag_name"
          done < Release_Commits.txt