name: Create Pull Request from Test Branch

on:
  push:
    branches:
      - test

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: test

      - name: Create new branch
        run: |
          git config --global user.name "Saurabh Talele"
          git config --global user.email "Saurabh.Talele@bentley.com"
          NEW_BRANCH="testing_branch_1"
          git checkout -b $NEW_BRANCH
          echo "Updated content on $(date)" >> test.txt
          git add .
          git commit -m "Automated update on $(date)"
          git push origin $NEW_BRANCH

      - name: Create pull request
        id: create_pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: test
          github_token: ${{ secrets.PAT }}
          pr_label: "feature, automated pr"
          pr_title: "[Example] Simple demo"


        # uses: peter-evans/create-pull-request@v6
    
        # with:
        #   github_token: ${{secrets.PAT}}
        #   base_branch: test
          

    
        # uses: peter-evans/create-pull-request@v5
        # with:
        #   token: ${{ secrets.PAT }}
        #   base: test
        #   head: ${{ steps.create-pull-request.outputs.branch }}
        #   title: "Pull request from test branch"
        #   body: "This is an automated pull request created from the test branch."
        #   commiter: Saurabh.Talele@bentley.com
      - name: Log pull request number
        run: |
          echo "Pull Request Number: ${{ steps.create_pr.outputs.pull-request-number }}"
