name: Create Pull Request from Test Branch

on:
  push:
    branches:
      - test

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: test

      - name: Create new branch
        run: |
          NEW_BRANCH="new-branch-$(date +%Y%m%d%H%M%S)"
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH

      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: test
          head: ${{ steps.create-pull-request.outputs.branch }}
          title: "Pull request from test branch"
          body: "This is an automated pull request created from the test branch."

      - name: Log pull request number
        run: |
          echo "Pull Request Number: ${{ steps.create_pr.outputs.pull-request-number }}"
