name: Create Pull Request from Test Branch

on:
  push:
    branches:
      - test
  workflow_dispatch:


jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: test2

      - name: Create new branch
        run: |
          git config --global user.name "Saurabh Talele"
          git config --global user.email "Saurabh.Talele@bentley.com"
    
          echo "Updated content on $(date)" >> test.txt
          git add .
          git commit -m "Automated update on $(date)"
          git push 

      - name: Create pull request
        id: create_pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: test2
          destination_branch: test
          github_token: ${{ secrets.PAT }}
          pr_label: "feature, automated pr"
          pr_title: "[Example] Simple demo"


      - name: Merge pull request
        uses: gsoc2/automerge-action@v0.16.3
        with:
            pull-request: ${{ steps.create_pr.outputs.pr_number }}
            token: ${{ secrets.PAT }}

        # uses: peter-evans/create-pull-request@v6
    
        # with:
        #   github_token: ${{secrets.PAT}}
        #   base_branch: test
          

    
        # uses: peter-evans/create-pull-request@v5
        # with:
        #   token: ${{ secrets.PAT }}
        #   base: test
        #   head: ${{ steps.create-pull-request.outputs.branch }}
        #   title: "Pull request from test branch"
        #   body: "This is an automated pull request created from the test branch."
        #   commiter: Saurabh.Talele@bentley.com
      - name: Log pull request number
        run: |
          echo "Pull Request Number: ${{ steps.create_pr.outputs.pr_number }}"
