name: Create Pull Request from Test Branch

on:
  workflow_dispatch:


jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref_name}}

      - name: Create new branch
        run: |
          git config --global user.name "Saurabh Talele"
          git config --global user.email "saurabhatalele@gmail.com"
          echo "Updated content on $(date)" >> test.txt
          git add .
          git commit -m "Automated update on $(date)" --author="Saurabh <saurabhatalele@gmail.com>"
          git push -f origin ${{github.ref_name}}

      - name: create PR
        run: |
          gh pr create --title "Release PR" --body "This PR is for the release." --head "${{ github.ref_name }}" --base main --label "release" --repo "actiontestorg/test"

      # - name: Create pull request
      #   id: create_pr
      #   uses: repo-sync/pull-request@v2
      #   env:
      #     GITHUB_ACTOR: "SaurabhATalele"
      #   with:
      #     source_branch: ${{github.ref_name}}
      #     destination_branch: main
      #     pr_label: "release"
      #     github_token: ${{ secrets.TOKEN_3 }}
      #     pr_title: "Release PR"
      #     pr_assignee: "SaurabhATalele"
      


      - name: Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
            github-token: ${{ secrets.PAT2 }}
            pull-request-number: ${{ steps.create_pr.outputs.pr_number }}
  
      - name: Auto merge PR
        uses: pascalgn/automerge-action@v0.16.3
         
        env:
            GITHUB_TOKEN: ${{secrets.PAT2}}
            MERGE_COMMIT_MESSAGE: "AUTO MERGER"
            MERGE_METHOD: merge
            MERGE_LABELS: "release" 
            
            
      - name: Log pull request number
        run: |
          echo "Pull Request Number: ${{ steps.create_pr.outputs.pr_number }}"
