name: Filter Commits

on:
  workflow_dispatch:

jobs:
  filter-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Filter commits
      run: |
        git log --pretty=format:"%H %s" | grep -E "[0-9]+\.[0-9]+\.[0-9]+" > filtered_commits.txt
        echo "Filtered commits:"
        cat filtered_commits.txt
