name: Restrict PRs to Main

on:
  pull_request:
    branches:
      - main

jobs:
  restrict-pr:
    runs-on: ubuntu-latest
    if: github.base_ref == 'main' && github.head_ref != 'dev'
    steps:
      - name: Check PR source branch
        run: |
          echo "Pull requests to 'main' are only allowed from 'dev' branch."
          exit 1
