name: Update File and Push

on:
  workflow_dispatch:
  push:
      branches:
        - dev

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Commit the bumped app package.json
      run: |
        echo "hello=hello" >> $GITHUB_ENV
    
    - name: print the env
      run: |
        echo $hello
        echo $GITHUB_ENV

    