name: Version Check

on:
  workflow_dispatch:

jobs:
  filter-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      pull-requests: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download EXE file
        run: |
          wget -O iTwinStudioforDevelopersSetup.exe https://autoupdatecdn.bentley.com/itwindesktopplatform/developer/iTwinStudioforDevelopersSetup.exe
        
      - name: install pev
        run: |
          sudo apt-get install -y pev
    
     
      - name: Get EXE Version
        run: |  
          echo "$(peres -v iTwinStudioforDevelopersSetup.exe | grep -i "Product Version" | awk '{print $3}')" > exe_version.txt
          cat exe_version.txt
          
      - name: print the version of the exe
        run: |
            echo "The version of the exe is ${{ env.exe_version }}"