name: Version Check

on:
  workflow_dispatch:

jobs:
  filter-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      pull-requests: write
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the installer version from change files
        run: |
            JSON_FILE="hoist-versions.json"
            version=$(jq -r 'to_entries | .[0].value' "$JSON_FILE")
            major=$(echo $version | cut -d. -f1)
            minor=$(echo $version | cut -d. -f2)
            echo "Version: $version" 
            echo "Major version: $major"
            echo "Minor version: $minor"

      - name: create release branch
        run: |
              set -e 
              git fetch --unshallow 
              git rev-list --all | while read commit_hash; do
                git checkout $commit_hash
                if [ -f pnpm-workspace.yml ]; then
                  echo "Checking commit $commit_hash"
                  yq e '.catalogs.hoisted' pnpm-workspace.yml | while read package version; do
                    major=$(echo $version | cut -d. -f1)
                    minor=$(echo $version | cut -d. -f2)
                    echo "Package: $package, Major: $major, Minor: $minor"
                  done
                fi
              done 
          