name: Version Check

on:
  workflow_dispatch:

jobs:
  filter-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      pull-requests: write
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the installer version from change files
        run: |
            JSON_FILE="hoist-versions.json"
            version=$(jq -r 'to_entries | .[0].value' "$JSON_FILE")
            major=$(echo $version | cut -d. -f1)
            minor=$(echo $version | cut -d. -f2)
            echo "Major version: $major"
            echo "Minor version: $minor"
          