name: Version Check

on:
  workflow_dispatch:

jobs:
  filter-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      pull-requests: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Download EXE file
        run: |
          wget -O iTwinStudioforDevelopersSetup.exe https://autoupdatecdn.bentley.com/itwindesktopplatform/developer/iTwinStudioforDevelopersSetup.exe
    
      - name: Install Wine
        run: sudo apt-get install -y wine

      - name: Get EXE Version
        run: |
          ls -l
          wine 
          ./iTwinStudioforDevelopersSetup.exe --version
          $exePath = "iTwinStudioforDevelopersSetup.exe"
          $versionInfo = (Get-Item $exePath).VersionInfo
          $version = $versionInfo.FileVersion
          $version
          echo $version
          echo "exe_version=$version" >> GITHUB_ENV
        shell: pwsh
    
      - name: print the version of the exe
        run: |
            echo "The version of the exe is ${{ env.exe_version }}"